Removed --fitMg, always fit Mg XI normalization instead.

diff --git a/src/00_Refit b/src/00_Refit
--- a/src/00_Refit
+++ b/src/00_Refit
@@ -12,90 +12,85 @@ ciao
 nproc=16
 
 for resp120c in '' yes; do
-    for fitMg in '' yes; do
-	export CONTAMID=$(./ciaostr)
-	fitMgopt=
-	resp120Copt=
+    export CONTAMID=$(./ciaostr)
+    resp120Copt=
 
-	[ "$resp120c" = yes ] && {
-	    CONTAMID+='-120C'
-	    resp120Copt='--120C'
-	}
-	[ "$fitMg" = yes ] && {
-	    CONTAMID+='_fitMg'
-	    fitMgopt=--fitMg
-	}
+    [ "$resp120c" = yes ] && {
+	CONTAMID+='-120C'
+	resp120Copt='--120C'
+    }
 
-	datadir=$(./datadir)
+    CONTAMID+='_fitMg'
 
-	for det in i3 s3; do
-	    export DET=$det
-	    obsids=$(obsids $det)
+    datadir=$(./datadir)
 
-	    [ "$resp120c" = yes -a "$DET" = s3 ] && continue
+    for det in i3 s3; do
+	export DET=$det
+	obsids=$(obsids $det)
 
-	    fitdir="$datadir/fits/$CONTAMID"
+	[ "$resp120c" = yes -a "$DET" = s3 ] && continue
 
-	    resdir="$fitdir/results"
-	    mkdir -p "$resdir"
+	fitdir="$datadir/fits/$CONTAMID"
 
-	    ./obs_info | tee $datadir/obs_info/$det.txt
+	resdir="$fitdir/results"
+	mkdir -p "$resdir"
 
-	    false && parallel -j $nproc ./specextract $resp120Copt ::: $obsids
+	./obs_info | tee $datadir/obs_info/$det.txt
 
-	    parallel -j $nproc ./gainfit $fitMgopt ::: $obsids
-	    gainfits_txt="$resdir/gainfits_${DET}.txt"
-	    perl ./compile_fit_results.pl gain $obsids | tee "$gainfits_txt"
-	    ./plot_gainfits "$gainfits_txt"
-	    psmerge_xspec gain
+	false && parallel -j $nproc ./specextract $resp120Copt ::: $obsids
 
-	    echo '.run shift_lines.pro'  | gdl -args $obsids
+	parallel -j $nproc ./gainfit ::: $obsids
+	gainfits_txt="$resdir/gainfits_${DET}.txt"
+	perl ./compile_fit_results.pl gain $obsids | tee "$gainfits_txt"
+	./plot_gainfits "$gainfits_txt"
+	psmerge_xspec gain
 
-	    # gdl never returns failure, so test that the output
-	    # line_shifts.xcm files are newer than gainfit.xcm
-	    for o in $obsids; do
-		obsid=$(printf %05d $((10#$o)))
-		line_shift_xcm="$fitdir/${obsid}/${obsid}_line_shifts.xcm"
-		gainfit_xcm="$fitdir/${obsid}/${obsid}_gainfit.xcm"
-		[ "$line_shift_xcm" -nt "$gainfit_xcm" ] || {
-		    echo "'${gainfit_xcm}' is newer than '${line_shift_xcm}'" 1>&2
-		    exit 1
-		}
-	    done
+	echo '.run shift_lines.pro'  | gdl -args $obsids
 
-	    parallel -j $nproc ./linefit $fitMgopt ::: $obsids
-	    linefits_txt="$resdir/linefits_${DET}.txt"
-	    perl ./compile_fit_results.pl line $obsids | tee "$linefits_txt"
-	    ./plot_linefits "$linefits_txt"
-	    psmerge_xspec line
-
-	    python3 ./plot_gain_corrections.py
-
-	    echo '.run data_shift.pro'  | gdl -args $datadir/obs_info/$DET.txt
-
-	    # gdl never returns failure, so test that the output
-	    # evt2_energy_shift files are newer than linefit.xcm
-	    for o in $obsids; do
-		obsid=$(printf %05d $((10#$o)))
-		evt2_energy_shift="$fitdir/${obsid}/${obsid}_evt2_energy_shift.fits"
-		linefit_xcm="$fitdir/${obsid}/${obsid}_linefit.xcm"
-		[ "$evt2_energy_shift" -nt "$linefit_xcm" ] || {
-		    echo "'${linefit_xcm}' is newer than '${evt2_energy_shift}'" 1>&2
-		    exit 1
-		}
-	    done
-
-	    parallel -j $nproc ./shift_pi ::: $obsids
-
-	    parallel -j $nproc ./shiftfit $fitMgopt ::: $obsids
-	    shiftfits_txt="$resdir/shiftfits_${DET}.txt"
-	    perl ./compile_fit_results.pl shift $obsids | tee "$shiftfits_txt"
-	    ./plot_shiftfits "$shiftfits_txt"
-	    psmerge_xspec shift
-
-	    python3 \
-		./plot_fit_results.py \
-		-p "$resdir/params_${DET}.pdf"
+	# gdl never returns failure, so test that the output
+	# line_shifts.xcm files are newer than gainfit.xcm
+	for o in $obsids; do
+	    obsid=$(printf %05d $((10#$o)))
+	    line_shift_xcm="$fitdir/${obsid}/${obsid}_line_shifts.xcm"
+	    gainfit_xcm="$fitdir/${obsid}/${obsid}_gainfit.xcm"
+	    [ "$line_shift_xcm" -nt "$gainfit_xcm" ] || {
+		echo "'${gainfit_xcm}' is newer than '${line_shift_xcm}'" 1>&2
+		exit 1
+	    }
 	done
+
+	parallel -j $nproc ./linefit ::: $obsids
+	linefits_txt="$resdir/linefits_${DET}.txt"
+	perl ./compile_fit_results.pl line $obsids | tee "$linefits_txt"
+	./plot_linefits "$linefits_txt"
+	psmerge_xspec line
+
+	python3 ./plot_gain_corrections.py
+
+	echo '.run data_shift.pro'  | gdl -args $datadir/obs_info/$DET.txt
+
+	# gdl never returns failure, so test that the output
+	# evt2_energy_shift files are newer than linefit.xcm
+	for o in $obsids; do
+	    obsid=$(printf %05d $((10#$o)))
+	    evt2_energy_shift="$fitdir/${obsid}/${obsid}_evt2_energy_shift.fits"
+	    linefit_xcm="$fitdir/${obsid}/${obsid}_linefit.xcm"
+	    [ "$evt2_energy_shift" -nt "$linefit_xcm" ] || {
+		echo "'${linefit_xcm}' is newer than '${evt2_energy_shift}'" 1>&2
+		exit 1
+	    }
+	done
+
+	parallel -j $nproc ./shift_pi ::: $obsids
+
+	parallel -j $nproc ./shiftfit ::: $obsids
+	shiftfits_txt="$resdir/shiftfits_${DET}.txt"
+	perl ./compile_fit_results.pl shift $obsids | tee "$shiftfits_txt"
+	./plot_shiftfits "$shiftfits_txt"
+	psmerge_xspec shift
+
+	python3 \
+	    ./plot_fit_results.py \
+	    -p "$resdir/params_${DET}.pdf"
     done
 done
