Added options --fitMg to {gain,line,shift}fit and --120C to specextract.

diff --git a/src/shiftfit b/src/shiftfit
--- a/src/shiftfit
+++ b/src/shiftfit
@@ -12,6 +12,34 @@
 
 set -eo pipefail
 
+TEMP=$(getopt -o 'h' --long 'fitMg,help' -- "$@") || {
+	echo 'Terminating...' >&2
+	exit 1
+}
+eval set -- "$TEMP"
+unset TEMP
+
+fitMg=
+
+while true; do
+    case "$1" in
+	'-h' | '--help')
+	    echo "Usage: $0 [-h|--help] [--fitMg] [obsid1 obsid2 ...]" >&2
+	    exit
+	    ;;
+	'--fitMg')
+	    fitMg=yes; shift; continue
+	    ;;
+	'--')
+	    shift; break
+	    ;;
+	*)
+	    echo 'Internal error, terminating' >&2
+	    exit 1
+	    ;;
+    esac
+done
+
 [ -z "$CONTAMID" ] && {
     echo "CONTAMID is not set, exiting" 1>&2
     exit 1
@@ -32,7 +60,7 @@ heainit
 
 model="$SCRIPTDIR/rgspn_mod_tbabs_tbvarabs_2apec_line_ratios_jd_v1.9.xcm"
 
-[ "$FITMG" = 'yes' ] && {
+[ "$fitMg" = 'yes' ] && {
     thaw37='thaw 37'
     conf37='error max 4.0 1. 37'
 }
diff --git a/src/specextract b/src/specextract
--- a/src/specextract
+++ b/src/specextract
@@ -5,6 +5,34 @@
 
 set -eo pipefail
 
+TEMP=$(getopt -o 'h' --long '120C,help' -- "$@") || {
+	echo 'Terminating...' >&2
+	exit 1
+}
+eval set -- "$TEMP"
+unset TEMP
+
+resp120C=
+
+while true; do
+    case "$1" in
+	'-h' | '--help')
+	    echo "Usage: $0 [-h|--help] [--120C] [obsid1 obsid2 ...]" >&2
+	    exit
+	    ;;
+	'--120C')
+	    resp120C=yes; shift; continue
+	    ;;
+	'--')
+	    shift; break
+	    ;;
+	*)
+	    echo 'Internal error, terminating' >&2
+	    exit 1
+	    ;;
+    esac
+done
+
 [ -z "$CONTAMID" ] && {
     echo "CONTAMID is not set, exiting" 1>&2
     exit 1
@@ -34,7 +62,7 @@ for obsid in $obsids; do
     fitdir="$datadir/fits/$CONTAMID/$obsid"
     bkgreg="$datadir/reg/bkg/${obsid}_bkg.reg"
     evt2="$reprodir/acisf${obsid}_repro_evt2.fits"
-    [ "$RESP120C" = yes ] &&  evt2="${evt2/evt2.fits/evt2-120C.fits}"
+    [ "$resp120C" = yes ] &&  evt2="${evt2/evt2.fits/evt2-120C.fits}"
     asol_stack=$(\ls -1 "$reprodir/../primary/"pcad*asol1.fits*  | perl -le 'chomp(@l=<>); print join ",", @l')
     pbk=$(\ls -1 "$reprodir/"*pbk0.fits*)
     msk=$(\ls -1 "$reprodir/acisf${obsid}"_*_msk1.fits*)
